### ISSUE TITLE
Unable to cancel CarryOn action

### ISSUE THREAD

**Issue by Sir-Will** [Tschipp/CarryOn#111]
CarryOn should fire Forge's BlockEvent.Break before attempting to pickup a tile to allow mods like protection mods to cancel this action.

**Comment by bloodmc** [comment]
This mod seems to have a hardcoded check for FTBUtils protection yet ignores other protection mods such as GriefPrevention. 

https://github.com/Tschipp/CarryOn/blob/master/src/main/java/tschipp/carryon/common/handler/PickupHandler.java#L194-L202

I'm assuming this check was added due to FTBUtils not listening to Forge's `BlockEvent.Break` even though it should be. To fix other protection mods that listen to Forge's break event, simply call the event and ignore the pickup if cancelled.

https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/event/world/BlockEvent.java#L115

**Comment by Tschipp** [comment]
Interesting. Will definitely look into it.

**Comment by bloodmc** [comment]
All plugins that require SpongeForge are loaded as mods in Forge.

Regardless of what is “well known”, Forge’s break event was added for this very reason.

**Comment by Tschipp** [comment]
Alright yeah will do

**Comment by Tschipp** [comment]
Thanks, this is added in the next release, I also added protections for entities using this method!
