### ISSUE TITLE
[1.12.2] Metal Chest support?

### ISSUE THREAD

**Issue by TheSnowyChickens** [Tschipp/CarryOn#124]
### Expected Behavior
Correct side from the lock, after end of carrying.

### Actual Behavior
It noted the lock side and dont rotate to the new placed side.

### Steps to Reproduce
Place the chest -> use carry on -> place the chest on a other block.

### Version of Minecraft, Carry On, Forge
1.12.2
Forge 2747
C.O.: v1.9.3
Metal Chest: v1.2.2

### Screenshots encouraged
![2018-08-05_20 14 30](https://user-images.githubusercontent.com/29357962/43688647-fa696698-98ec-11e8-9724-1a3d099abe5b.png)

![2018-08-05_20 14 36](https://user-images.githubusercontent.com/29357962/43688648-fc71612a-98ec-11e8-84cb-938dece37977.png)

![2018-08-05_20 14 42](https://user-images.githubusercontent.com/29357962/43688651-fe55894e-98ec-11e8-91ce-2de036d23b7b.png)

**Comment by Tschipp** [comment]
CarryOn  can only do rotation if mods implement one of the vanilla ways how rotation is handled. I'm gonna take a look at it but I'm pretty sure there's nothing I can do about it.

**Comment by TheSnowyChickens** [comment]
Oh okay, then I report this problem to the Metal Chest developer.

Thx for this info. :)

**Comment by T145** [comment]
@Tschipp Do you utilize `rotateBlock` anywhere? All I see is reference to setting `PropertyDirection` ([https://github.com/Tschipp/CarryOn/blob/master/src/main/java/tschipp/carryon/common/item/ItemTile.java#L118](https://github.com/Tschipp/CarryOn/blob/master/src/main/java/tschipp/carryon/common/item/ItemTile.java#L118)).

**Comment by Tschipp** [comment]
Wow, no I was unaware of the method. I will implement it in the next release. Thanks for the info.

**Comment by Tschipp** [comment]
So after taking a closer look at `rotateBlock`, I sadly must come to the conclusion that I cannot use it for my purposes, as its implementation depends entirely on the modder that implements it. See this comment of the method:
```
Rotate the block. For vanilla blocks this rotates around the axis passed in (generally, it should be the "face" that was hit).
Note: for mod blocks, this is up to the block and modder to decide. It is not mandated that it be a 
rotation around theface, but could be a rotation to orient *to* that face, 
or a visiting of possible rotations.
The method should return true if the rotation was successful though.
```

If we imagine that every modder implements it like vanilla does, to rotate the block correctly I would need to do this: (keep in mind this would also only be for y-axis rotation)
1. Check the rotation of the block when it was picked up
2. call `rotateBlock` until the block faces the player.

However, to be able to know at what rotation the block is currently on when being picked up (step 1), I need to get its PropertyDirection. Now, if the block handles rotation in NBT, this won't be possible and it will be impossible for me to know, how many times I need to call `rotateBlock` so that it faces the player.

I also thought about resetting the rotation to a "default rotation", so that I always know how many times I need to rotate, just based on the player. But that method also requires knowledge about the current rotationstate of the block.

Realistically, most modders won't all write `rotateBlock` in the vanilla way either way, so that ruins the method I described above.

So sadly, I think I'm gonna have to stick with my ugly method, because it works. Unless I've missed something major, I don't think it's possible with `rotateBlock`. If you have any suggestions of how I might do it, I'm all ears! @T145

**Comment by T145** [comment]
Do something like ChestTransporter, where there's a developer API that handles how the block is rotated. This is basically like that mod, w/ the exception of being able to use your arms.

As for `rotateBlock`, if you inspect the actual method, you'll realize it's extremely to what you already do when placing the chest. You're overthinking this way too much. The vanilla way uses `PropertyDirection`, which is what you're doing right now. If someone implements the method themselves, then it just does something else. You don't need to worry about the NBT at all. It's on the other developer to implement the method in their block to adjust their tile's NBT. Here's what you do:
1. Remove the `while-loop` here: [ItemTile.java#L110](https://github.com/Tschipp/CarryOn/blob/master/src/main/java/tschipp/carryon/common/item/ItemTile.java#L110)
2. Replace it w/ setting the `set` boolean equal to `rotateBlock`'s result
3. You've got it from here

- [TransportableChest.java](https://github.com/cubex2/chesttransporter/blob/master/src/main/java/cubex2/mods/chesttransporter/api/TransportableChest.java)

**Comment by Tschipp** [comment]
I see, but rotating the block is not the problem. The problem is, how many times we need to call `rotateBlock`. Let me make an example:
If we pick up a chest that is facing south (the player is facing north), and the player places it back down while facing south, the chest needs to be rotated to face north. That means, we need to call `rotateBlock` twice, and rotate it around the y-axis. 
To be able to calculate how many times we need to rotate the block so that it faces the player correctly, we need to somehow figure out what the rotation of the block was, before it was picked up. If blocks handle rotation in the vanilla way, this can be done easily by just getting the rotation property. But in case of modded blocks that don't handle their rotation with states but with nbt, there is no way to know in what direction the block was facing before the pickup, because there sadly is no `getRotation` method (as least as far as I know. If you know a way to get the rotation of any block, please let me know!). 
So if we cannot determine at what rotation the block was at before the pickup, there is no way to know how many times we need to call `rotateBlock` in order to make the block face the player properly.

**Comment by TheSnowyChickens** [comment]
Is this maybe 1 problem? MC dont have this 1 tag in F3.
![facing](https://user-images.githubusercontent.com/29357962/44092095-bb130c1c-9fcf-11e8-83a7-228a722e60dc.png)

**Comment by Tschipp** [comment]
No. The problem is that there is no way for me to retrieve the rotation of a block, that stores its rotation in NBT.

**Comment by TheSnowyChickens** [comment]
@T145 before I open a new issue at your Github (because the topic is suitable here), I can see, that the Thermal Foundation crescent hammer cant not rotate your chests either. (but vanilla chests)

So as an idea for CarryOn, is maybe behind the Thermal F. crescent hammer some usefull code?

**Comment by Tschipp** [comment]
I will take a look at their code

**Comment by T145** [comment]
> To be able to calculate how many times we need to rotate the block so that it faces the player correctly, we need to somehow figure out what the rotation of the block was, before it was picked up.

Just use `player.getHorizontalFacing().getOpposite()`.

**Comment by Tschipp** [comment]
> Just use player.getHorizontalFacing().getOpposite()
Well yes, that is the target facing of the block after it has been placed down. But that still doesn't tell me anything about the rotation of the block before I picked it up.

**Comment by T145** [comment]
My point is that you don't need that information. Just the direction facing the player.

**Comment by Tschipp** [comment]
> My point is that you don't need that information. Just the direction facing the player.

How so? That just tells me what direction the block should be facing after I've placed it down. It tells me nothing about how many times I need to call `rotateBlock`

**Comment by T145** [comment]
Ok I see your issue. You want to get the initial facing value so you can determine if it's an opposite side, and therefore needs two rotations. This information cannot be easily retrieved from a tile entity (unless you set up a simple `IFacing` interface or something *cough*). If you need to get a value from NBT, set up a `HashSet` of all the likely values for linear checks:
```java
HashSet<String> facingValues = new HashSet<>();
facingValues.add("facing");
facingValues.add("Facing");
facingValues.add("front");
facingValues.add("Front");
facingValues.add("orientation");
facingValues.add("Orientation");
```
Check to see if there's any match. The HashSet will allow for O(1) checks. If we get a match, then we need to determine what data type it is. It can either be a String, Integer or Byte. Of course that would just be something like:
```java
if (facingTag instanceof String) {
    return EnumFacing.valueOf((String) facingTag);
} else if (facingTag instanceof Integer) {
    return EnumFacing.getIndex((Integer) facingTag);
} else if (facingTag instanceof Byte) {
    return EnumFacing.getIndex((byte) facingTag);
}
```
Now you have the `EnumFacing` value; check if it's opposite, and rotate twice if so, else just one time.

**Comment by Tschipp** [comment]
Hmm... yeah that seems doable. Ok, I will include a check for common NBT values for rotation!

**Comment by TheSnowyChickens** [comment]
Thank you guys! 👍  

For me, adding this feature has sounded so easy, but now I saw that it didn't seem that way.
(I had basic Java in school^^)

**Comment by Tschipp** [comment]
Heey, it works! 
[gif](https://i.gyazo.com/f9ba983670b244b0ff7020886e260f29.gif)
@T145 Thank you for your support!

**Comment by T145** [comment]
You're welcome :P
