### ISSUE TITLE
Chest pickup allows for triple chest

### ISSUE THREAD

**Issue by democat3457** [Tschipp/CarryOn#238]
Info here:

https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/323

**Comment by Tschipp** [comment]
Well... may I ask how you discovered this? When I wrote this "fix" for the situation where the player dies while carrying, I knew that things like this could happen, but I went with it anyway because it's such a rare case and frankly I don't really see a better way to do it.
I guess I could search for a larger area to place the chest, but that also doesn't solve the problem, just make it more unlikely. 
What do you suggest?

**Comment by democat3457** [comment]
Well, I feel like it's really just cheese for the sake of cheese... I guess it could replace a block? Or, if it's possible, just make the chests not connect? I don't really know, like you said, it's more of an edge case... (I was hoping you'd have some ideas lol)

**Comment by Tschipp** [comment]
mhh I think replacing a block could lead to even worse bugs, like destroying unbreakable blocks or something like that. I guess I'll just increase the search range and try to find a better spot to place it. Did you find this bug by just playing or by going through the code?

**Comment by democat3457** [comment]
By playing, main intent was to see if it could be cheesed...

**Comment by democat3457** [comment]
> I guess I'll just increase the search range and try to find a better spot to place it.

Update?

**Comment by Tschipp** [comment]
I have not worked on it yet.

**Comment by democat3457** [comment]
boop

**Comment by Tschipp** [comment]
I have not worked on it yet, and it is not a priority either frankly. It causes no duplication glitch or anything, just some messy visuals.

**Comment by democat3457** [comment]
Ah ok. Gotcha.

**Comment by Tschipp** [comment]
I will now mark this as resolved. For 2.0.0, this can still happen but is very improbable.
