### ISSUE TITLE
jukebox music isnt moving with player

### ISSUE THREAD

**Issue by avihu2929** [Tschipp/CarryOn#284]
### Expected Behavior
when picking up jukebox music will follow the player location

### Actual Behavior
music is stuck at the intial pick up position

### Version of Minecraft, Carry On, Forge
last version

**Comment by Tschipp** [comment]
Fixed in next release, but there now is a deeper issue, the jukebox "forgets" that it has a record inside. If you break it, you still get the record, but if you try to right click it to get the other record out it doesn't work. If you try to insert another record, the old one is  overwritten. I'll have to fix this another time.

**Comment by Tschipp** [comment]
related to #287
