### ISSUE TITLE
Cannot carry anything

### ISSUE THREAD

**Issue by TheBarrelGod** [Tschipp/CarryOn#315]
### Expected Behavior
To carry objects
### Actual Behavior
Does nothing
### Steps to Reproduce
Try to carry
### Version of Minecraft, Carry On, Forge
1.16.5, carryon-1.16.5-1.15.3.13, forge 36.1.1

**Comment by Tschipp** [comment]
Could you elaborate a bit on what exactly is happening and what you're doing? What keys are you pressing?

**Comment by TheBarrelGod** [comment]
I have empty hand and offhand. I am pressing the bound button and right click. I have changed the bound button twice to no avail.
The chest has been broken and replaced crafted a new one. Made a new save. Reloaded the mod. Nothing works

**Comment by RiverC** [comment]
Can confirm this. Switching the keybind doesn't seem to help. When I try to interact with a container while holding the carry key, it just opens the container (both hands are empty.) Same version as above.

EDIT: I want to add to this, since it may be helpful. It works on mobs still, there just seems to be a problem with tile entities like chests.

**Comment by GrenHubber** [comment]
i can only pick up entities from the Vehicle mod by MrCrayFish
