### ISSUE TITLE
Carry on ftb ultmine incompatibility

### ISSUE THREAD

**Issue by Alonlystalker** [Tschipp/CarryOn#337]
### Expected Behavior
hold shift carry blocks

### Actual Behavior
hold shift destroying blocks

### Steps to Reproduce
flt ultmine button set to shift carry on button also set to shift

### Version of Minecraft, Carry On, Forge
1.16.5 latest forge and carryon

this works badly only if both mods have same active button, carry on dont carry any block just instantly destroying them.

**Comment by Gunner76th** [comment]
This isnt a compatibilty issue with FTB Ultimine, this is a keybind issue. This would happen with virtually any mod that had a similar keybind. And its possible that carry on is activating but because the block is mined away, you don't see it. Resolve this by not using the same key for multiple things. FTB Ultimine should not be set to the same key as ANYTHING.

**Comment by Tschipp** [comment]
Exactly. Also, carry on can be rebound, and I'm sure ultmine can too.
