### ISSUE TITLE
Disconnects from LAN when putting a entity (or whatever) down.

### ISSUE THREAD

**Issue by dasRAINBOW** [Tschipp/CarryOn#410]
### Expected Behavior
Not disconnecting.

### Actual Behavior
Disconnecting me from the LAN when a entity gets placed down.

### Steps to Reproduce
Play on LAN and have a second account put down a entity.

### Version of Minecraft, Carry On, Forge
Minecraft 1.19
Forge 41.1.0
Carry On 1.19-1.18.1.2

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/69715079/183924274-68846af9-b6e7-488a-b257-cf8ceb74a6d0.png)

**Comment by Tschipp** [comment]
I'm gonna need a full log

**Comment by pedroolivagil** [comment]
Hello @Tschipp, I am another user and I have the same problem. The log is difficult to obtain from the minecraft logs.

I have downloaded the code from this repository to my local and I have done some tests debugging the code, but I have not been able to find where the error is thrown. The error it throws is IndexOutOfBounds and it seems to come from a thread.

To reproduce the error I had to launch 2 instances of minecraft and join them in lan (open minecraft lan). Then the client (the one that connects to the host) that connects to the host (the one that shares the lan game) disconnects as soon as one of the 2 is picking up and leaving entities, normally it happens when the entity leaves and not when catch it, throwing the error.

As errors occur, it also counts to connect both games in lan. When I have a while, if I can I'll upload the log that the console paints, but this way you can try and locate the error that will be easier for you than for me since it is your code.

I hope this helps you solve it!

Thanks and regards!

**Comment by Tschipp** [comment]
Sorry, I can't solve it without a log when the issue happens, I can't reproduce it myself.
