### ISSUE TITLE
[1.19.2] Unable to pick up anything 

### ISSUE THREAD

**Issue by itsdinkd** [Tschipp/CarryOn#457]
### Expected Behavior
Picking up blocks and entities that are not in the blacklist

### Actual Behavior
Unable to pick up anything

### Steps to Reproduce
1. Use config
2. Set keybind
3. Try to pick up a Minecraft chest

### Version of Minecraft, Carry On, Forge
Fabric, v2.0.4.6

Config used: https://pastebin.com/jj1PUc7p

**Comment by volrathstormborn** [comment]
Getting the same issue.  I updated the FTB DW20 modpack from version 1.1.0 to 1.2.1 bringing Forge from 43.1.57 to 43.2.3 which broke the last working version I had in use for Carry On - 2.0.0.5 which I added manually.  I tried the latest version for 1.19.2 as of today which did not work, and I even went back to version 2.0.2.3 which was the next version for Forge and MC 1.19.2 after the date posted for the 2.0.0.5 file upload (there was one other in between).  I'm sure you can see I'm winging this one from the hip without the Curseforge Site pages up.

The key options show up, and I'm not seeing any further errors for carry on.  I understand these are different versions of the mod being Fabric/Forge but the issue remains the same so I decided to post here anyway.

**Comment by Tschipp** [comment]
@itsdinkd do you have a modpack or list of mods that I can try?

**Comment by Tschipp** [comment]
@rickhovanec Just to clarify, you used 2.0.5.10?

**Comment by itsdinkd** [comment]
> @itsdinkd do you have a modpack or list of mods that I can try?

Yes. Another Quality Modpack 2

**Comment by volrathstormborn** [comment]
> @rickhovanec Just to clarify, you used 2.0.5.10?

I used:

carryon-forge-1.19.2-2.0.2.3.jar  (in case FTB didn't update Forge to current)
carryon-forge-1.19.2-2.0.5.10.jar

Never know with these modpacks and since it was in the 1.18.2 pack I got used to having it.  They did not add it to the 1.19.2 pack but with no dependencies I dropped it into my server.  I know it was good prior to the update, and they updated Forge to add Botania so I tried a couple versions with no luck.

**UPDATE!!  Just got it working**  So to get you fresh logs I removed v2.0.2.3 and re-added v2.0.5.10.  Checked the logs and now I see it recreating the config files (though the data is almost identical).  I logged in, validated the keybind, and tested it on a Mob Grinder Utilities jumbo tank which works great.  Checked more blocks and Forge version in fine.

Here's to hoping it wasn't me where the configs had to be deleted, or a false positive report wasting anyone's time.

**Comment by Tschipp** [comment]
@itsdinkd I tried this pack and the config and I cannot reproduce this. It works fine when I tried to pick up a chest.

**Comment by itsdinkd** [comment]
Did you set a keybind? I set the carry on keybind to middle mouse and
nothing happens when using it.

**Comment by Tschipp** [comment]
Ah, the keybind is not compatible with mouse keys

**Comment by Tschipp** [comment]
Keep in mind, you still need to right click apart from pressing the carry key. So it's not really practical to have it bound on the mouse.

**Comment by itsdinkd** [comment]
Ah that's why. Thanks for the clarification

**Comment by Tschipp** [comment]
@rickhovanec Was this the problem for you too?

**Comment by volrathstormborn** [comment]
> @rickhovanec Was this the problem for you too?

Yeeeaaahh….absolutely not. 🤦‍♂️

The first couple changes of versions didn’t register correctly with Mixin, but that last time to grab logs ran without error. 

May have needed a couple more server restarts. Couldn’t say, but I’m certainly aware of how to use the mod. Adding it myself though I’m finding a lot more items that will need to be added to allowed or removed from the blacklist because there are a lot more items that I used to be able to pickup that I no longer can. But that’s on me to configure.

**Comment by Jurajov** [comment]
Carryon works for my teammates, but not for me. We have the same everything. What could be the problem?? 1.19.2
