### ISSUE TITLE
Left-Shift pickup completely disables sneaking in Fabric

### ISSUE THREAD

**Issue by ghost** [Tschipp/CarryOn#483]
### Expected Behavior
 - In my Forge modpack I can have both sneak and pickup on the Left Shift button, and they will both work fine.

### Actual Behavior
 - In my Fabric modpack if I put Carry On on Left Shift I can no longer sneak. If I change the button for Carry On, sneaking works fine.

### Steps to Reproduce
 - Set Carry On in Fabric on Left Shift and try to sneak without picking anything up.

### Version of Minecraft, Carry On, Forge/Fabric
 - Minecraft 1.19.2
 - Fabric 0.14.18
 - Carry On 2.0.4.6

**Comment by Tschipp** [comment]
As far as I know, this is because fabric handles keybind conflicts differently than forge. With forge, even when there is a conflict, both sneaking and pickup can still function. That's why on fabric, I set the key to "None" by default (hitting escape when selecting key), which then defaults to check for sneaking instead of a specific key. This is a dirty workaround, so I'd love to know if there's a better way around this.

**Comment by SplendidAlakey** [comment]
May I suggest an optional dependency on something like [Amecs](https://www.curseforge.com/minecraft/mc-mods/amecs)? It's especially problematic for me, because I'm using another mod, that sets its interaction to crouch + right-click for editing signs, but Carry On takes priority and makes me pick it up, instead.

It's actually already possible for this mod to work with Amecs, but the keybind gets reset automatically, even if you change it. You can change it for a session (or until you visit the options again), but then it'll get reset.

Therefore, all you'd really have to do is declare Amecs an optional dependency, which if present will change the way you handle the keybind from the way it is now to how it is on Forge.

Edit: I was actually able to prevent the keybind from resetting by changing it in options.txt, rather that in game, so now I'm able to both sprint and pick up stuff with left shift and Amecs.
