### ISSUE TITLE
Scary looping sound when picking something up

### ISSUE THREAD

**Issue by Denixerianer** [Tschipp/CarryOn#591]
### Expected Behavior
No sound

### Actual Behavior
There is a very eery and scary looping sound when picking up anything. Makes me scared to pick anything up. This sounds like a joke but it is not, this really is happening and 100% only when picking something up.

### Steps to Reproduce
Pick something up and have sound on

### Version of Minecraft, Carry On, Forge/Fabric
1.20.1, 2.1.2.7, Forge

### Screenshots encouraged
Im not sure how or where to upload sound recording

**Comment by WarrLord47** [comment]
Just installed the mod and I'm also getting a scary looping sound whenever I pick something up.

**Comment by FirstL1ght** [comment]
I found out that this problem occurs when mod [ExtraSounds](https://modrinth.com/mod/extrasounds) is installed.

**Comment by 3ncanis** [comment]
Happens to me as well, can confirm disabling ExtraSounds (in my case this version https://modrinth.com/mod/extrasoundsforge) makes the sound stop.

[Here's a video of the sound it's ominous asf](https://streamable.com/t4a53n)

**Comment by WarrLord47** [comment]
I found a workaround by using another mod called Sounds Be Gone, which makes a log of every sound played around you and allows you to open a menu and disable them completely on the spot. Using this I found the scary sound to be two sounds, "extrasounds:effect.add.negative" and "extrasounds:effect.remove.negative". Muting these stopped the sound for me.

**Comment by 3ncanis** [comment]
Thank you!

**Comment by nco2k** [comment]
its because CarryOn applies a silent slowness effect when you pick something up, and ExtraSounds plays a sound when you have an effect on you. you should report this to ExtraSounds, and ask them to not play sounds for silent effects. alternatively you could use the [Sounds](https://modrinth.com/mod/sound) mod instead of the ExtraSounds mod. it used to have the same issue, but it got fixed recently.

this issue should be closed now, because the problem lies on the mods playing those sounds.

**Comment by Tschipp** [comment]
I agree, thanks for the comments
