### ISSUE TITLE
Carry On not working in version 1.21 for Forge

### ISSUE THREAD

**Issue by MamboGamesStudios** [Tschipp/CarryOn#667]
### Expected Behavior

     Be able to access Minecraft with the mod (Carry On 1.21 for Forge) installed.

### Actual Behavior

     Does not allow access to the game.

### Steps to Reproduce

     1. Install the Mod in the Mods folder.

     2. Start Minecraft 1.21 with version (Forge 51.0.29).
  
     3. The screen shows a message with Error code: 1

### Version of Minecraft, Carry On, Forge/Fabric

     Minecraft 1.21

     MOD: Carry On

    Forge 51.0.29

### Screenshots encouraged

<img width="1592" alt="image" src="https://github.com/user-attachments/assets/692925fb-7eb8-4bdb-ac10-cdf8a2341d60">

**Comment by rventxz** [comment]
same problem

**Comment by Zilgyd** [comment]
Same problem but in server with forge version1.21-51.0.33, the server doesn't start

**Comment by devmxlx** [comment]
The screenshot you uploaded seems to show a report of an issue regarding a Minecraft mod (`Carry On`) not working with Minecraft 1.21 and Forge 51.0.29. The error is causing the game to crash with a message that says "Error Code: 1" in Spanish ("El juego ha dejado de funcionar" translates to "The game has stopped working").

This error is common when there's a mod incompatibility, incorrect Forge version, or missing dependencies.

Here are some suggestions to troubleshoot the issue:

1. **Verify Mod Compatibility**:
   - Ensure that the version of the `Carry On` mod you are using is specifically designed for Minecraft 1.21 and Forge 51.0.29. Mods often need to be updated to match the latest game version.

2. **Check for Missing Dependencies**:
   - Some mods require additional mods or libraries (e.g., `Mantle`, `Baubles`) to run. Confirm that all dependencies are installed correctly.

3. **Update Forge**:
   - Consider updating Forge to a newer version if available. It’s possible that the mod requires a more recent Forge version, or that the version you’re using is unstable.

4. **Test with Only the Mod**:
   - Temporarily remove all other mods except for `Carry On` and see if the game still crashes. If it does, then the problem is likely with this mod. If not, there could be a conflict with another mod.

5. **Check Logs for Details**:
   - Minecraft's crash logs can provide detailed information about what’s causing the crash. Look for the `latest.log` or `crash-reports` files in your `.minecraft` directory.

6. **Redownload the Mod**:
   - There’s a chance that the mod file is corrupted. Redownload the `Carry On` mod from a reliable source and try again.

If the issue persists after these steps, sharing the crash log file or more details from the log could provide more insights.

**Comment by aleopeo** [comment]
pudiste? si pudiste dime como porfa
