### ISSUE TITLE
Modern Industrialization pipes can get picked up, breaking pipes

### ISSUE THREAD

**Issue by CommanderTso** [Tschipp/CarryOn#677]
### Expected Behavior
Carry On won't pick up MI pipes.

### Actual Behavior

It's possible to pick up MI pipes with Carry On (and can be likely, since modifying pipes often has you crouching and interacting), which then breaks that block location.  Pipes can't be replaced, and both the MI debug pipe removal and the vanilla /fill command won't fix the issue

### Steps to Reproduce 
* Lay down some MI pipes
* Pick up a section of pipe

### Version of Minecraft, Carry On, Forge/Fabric
Minecraft 1.20.1
Carry On v2.1.2.7
Modern Industrialization v1.8.4
Fabric 0.16.3

### Screenshots encouraged
![2024-08-27_09 25 30](https://github.com/user-attachments/assets/40362f14-bf7d-4b0c-af35-9ba19f716c1b)

### Notes
* I'm not sure if this is as simple as adding a new disallow to the pack - going to see if I can do that for myself now. But I figured it might be a good one to include in the release config
* Originally saw this on our Prominence 2 server, but made sure to test this in a bare-bones setup as listed above.

**Comment by CommanderTso** [comment]
Did a quick search of MI items and added all the ones that looked even vaguely cable-ish to the blacklist in carryon-common.json on our server.  After a restart, the couple kinds of cable I had on me were no longer pick-up-able.  I added:

```
      "#modern_industrialization:item_pipes",
      "#modern_industrialization:fluid_pipes",
      "#modern_industrialization:me_wires",

      "modern_industrialization:copper_cable",
      "modern_industrialization:tin_cable",
      "modern_industrialization:aluminum_cable",
      "modern_industrialization:cupronickel_cable",
      "modern_industrialization:silver_cable",
      "modern_industrialization:electrum_cable",
      "modern_industrialization:annealed_copper_cable",
      "modern_industrialization:platinum_cable",
      "modern_industrialization:kanthal_cable",
      "modern_industrialization:superconductor_cable",
```

Thanks!  Your mod is brilliant, by the way.  Especially in conjunction with dealing with MI and having blocks containing thousands of resources.

EDIT - Just accidentally picked up a white fluid pipe, even with the `#modern_industrialization:fluid_pipes` entry above.  Not sure if I did something wrong, or if this won't work the way it's in there; I was assuming a tag would work since there are similar tags in the blacklist, but maybe not.  I'll look at this more when I have time.

**Comment by ridesdragons** [comment]
can confirm this issue. accidentally created an elephant's foot in the server I'm playing in, wound up burying it in cement. we have found that any block that is able to break other blocks (such as ae2's annihilation panes) will break the fake pipes and allow you to place blocks in that tile again, but you still can't place wires or pipes there (or next to it). filling the corrupted tiles and a 1 block +-shaped radius with cobble prevents it from causing other issues, but it's still unfortunate, as it was in the middle of my factory setup.

with some testing in creative mode, I found that you can actually "fix" the corrupted tiles, but only by creating other corrupted tiles. if the corrupted tile is currently "empty" (either due to block-breakers or from you not having attempted to place a pipe in there yet), you can pick up and place a pipe in the corrupted tile to fix it, but that requires picking up a pipe from another tile, which will just turn that other tile into a corrupted tile. so you can move the corruption, but can't get rid of it.

as for the config, though, I can't actually get the config to work. does carryon-common.json not apply in singleplayer? I can't get either my compact version or the expanded version like you have to work.

here's a more compact version of the lines you need to add to account for the different pipes and cables, btw
```
      "modern_industrialization:*_cable",
      "modern_industrialization:item_pipe",
      "modern_industrialization:*_item_pipe",
      "modern_industrialization:fluid_pipe",
      "modern_industrialization:*_fluid_pipe",
```
should account for all cables and pipes (except for ME wires). if this doesn't work, then the "*_item_pipe" like just needs to be expanded to account for all the dyed colours, such as "white_item_pipe" and "blue_item_pipe". you can alternatively find the exact item IDs in Modern-Industrialization-1.8.4.jar\data\modern_industrialization\tags\items (cables require visiting recipes\materials instead, but you already wrote a list of the possible cables above, so that's not necessary)
