### ISSUE TITLE
I can't pick up tile entities!

### ISSUE THREAD

**Issue by Sunconure11** [Tschipp/CarryOn#70]
### Expected Behavior

Ability to pick up tile entities

### Actual Behavior

Only entities can be picked up

### Steps to Reproduce

Try and carry a chest

### Version of Minecraft, Carry On, Forge

14.23.1.2601 for forge, 1.12 minecraft, v1.7.1 for Carry On

**Comment by Tschipp** [comment]
oh dear. Checking it out

**Comment by Sunconure11** [comment]
My config:

https://pastebin.com/vs8vvHKg

**Comment by Tschipp** [comment]
Have you rebound the carry key?

**Comment by Sunconure11** [comment]
The carry key appears to be conflicting with another key, but it is using the default settings.

**Comment by Tschipp** [comment]
I really don't know, it works for me. Can you try it on a new instance? Are you using Java 8?

**Comment by Sunconure11** [comment]
I am using Java 8, yes. I will test it on a new instance, not sure what is going on.

**Comment by Tschipp** [comment]
Alright cool

**Comment by Tschipp** [comment]
I took a look at it and managed to pinpoint the issue: I used a newer, yet unreleased version of FTBU. This version had some changes which weren't available in the version on curseforge. I fixed it now.

However, I noticed other issues:
Picking up a block seems to also almost instantly place it down again, unless you don't aim at the block. 
I managed to only pick it up and not place it down, but only if I clicked my mouse very quickly - quite hard to do consistently.
This is strange, because this isn't how right-click events work in vanilla or even in normal forge. You click (and hold!) once, the event fires once. However with your pack, you click and hold, and the event fires as long as you're holding.
It seems as if repeating mouse events are turned on. 
But at the same time, holding right click with a block in hand, to place that block, doesn't work. It places one or maybe two blocks, but then stops. This also isn't vanilla behavior. I have no Idea which mod could cause this... but I don't think It's Carry On.

The other issue that I checked was one that you reported on earlier, #63. In fact, it is as I suspected.
Twilight Forests adds these Ice-Blocks. They can be seen when manually giving the player slowness via commands, but only very briefly at the start.
However, again, I wasn't able to replicate that bug in a new instance with just Carry On and Twilight Forest. So I don't think any one of them is at fault. Would you know of a mod in your pack that messes with effects?

**Comment by Sunconure11** [comment]
I have a mod that does change how blocks can be placed.

https://minecraft.curseforge.com/projects/better-placement?gameCategorySlug=mc-mods&projectID=278406

As for messing with potion effects, I am unsure, though a bunch of mods in the pack are used that add their own effects.

**Comment by Tschipp** [comment]
Yep it’s probably that mod that breaks it. What a shame. Don’t know what to do about it.
Also I noticed another thing: the mod that adds more hotbars, I dunno the name, seems to be quite broken. When you expand the hotbars all guis slide upwards and it gets really annoying.

**Comment by Sunconure11** [comment]
That's quark.

**Comment by Tschipp** [comment]
Quark? A bug that bad is in quark? :0

**Comment by Sunconure11** [comment]
The hotbars are from quark. It's literally not a bug.

**Comment by Rikshy** [comment]
I have the same issue in my custom pack. 

Better Placement is installed but Quark not.

Disabling Quark doesnt solve the issue tho :(

**Comment by Rikshy** [comment]
Just tested mods that could cause the issue, the realized you already found it was/is FTBU.

sorry.

**Comment by Tschipp** [comment]
I'm releasing an update today that fixes FTBUtils and provides a (hopefully) temporary fix for better placement

**Comment by Ace-7642** [comment]
So what exactly is causing this to happen there are multiple ftb mods that are out there and i have three of them
