### ISSUE TITLE
Request: Paste into 1.7.10 modding environment and see if it works PLS!

### ISSUE THREAD

**Issue by lilgandhi1199** [Tschipp/CarryOn#71]
I could get any number of overpowered mods to capture mobs in eggs or some nonsense and install jabba for it's dolly feature but it also allows you to carry an infinite number of full chests all at once. I can carry 64 empty chests and carry 1 full chest but I'm not strong enough for 28 full ones. ;)

Anyways I'd really appreciate if you gave it some thought!
Take care

**Comment by Tschipp** [comment]
Hey, the code doesn’t work on any versions pre 1.8. In 1.8, the rendering of blocks was completely overhauled and changed to the system that we have currently. I would have to rewrite most of the mod. And frankly I don’t know how to do something as complex as this on 1.7.10
Not to mention the fact that forge doesn’t support 1.7.10 any longer, which means I couldn’t get support from the Forge forums.

So overall, my answer would have to be no, because it is simply too much work. I suggest you move on to newer versions, there are so many new amazing mods that easily replace the lost mods from 1.7.10.

**Comment by lilgandhi1199** [comment]
Thank you for the consideration. That would definitely be hard. You'd have to break open any number of mods to find out how it's done. I'll just recompile it after removing all rendering stuff because it's all about function for me

**Comment by Tschipp** [comment]
Sure, you can try that, but just please don't release it anywhere
