### ISSUE TITLE
1.12.2 v1.8 causes server to crash saying ftbu 5 is missing

### ISSUE THREAD

**Issue by kreezxil** [Tschipp/CarryOn#90]
### Expected Behavior

Server not to crash
### Actual Behavior
server crashes

### Steps to Reproduce
install mod on server

### Version of Minecraft, Carry On, Forge
1.12.2 
1.12.2 v1.8
14.23.2.2640

The mod page doesn't say that FTB Utilities is required. Was it not supposed to be compiled in the mod itself?

crash report:
https://gist.github.com/3a3ffc77db8753baa7a5656679f6c2a3

fml server latest:
https://gist.github.com/661ab69cb4abdf3bbd24d284168c167f

**Comment by Craftplacer** [comment]
Short answer: no
Long answer:
Mods usually write their mod dependencies in the about/info page, but no mod ever includes another mod it's usually the user's job to do.

But another note, if you downloaded it from Twitch/Curse(Forge) you should've looked into the dependencies tab.

**Comment by Tschipp** [comment]
Do you have FTB Utilities on your server? Because that message would only show up if you already had FTBU, but it was an outdated version

**Comment by kreezxil** [comment]
carry on didn't require it until now. yes I have the outdated version for a
very good reason, the newer versions of FTB Utilities are broken. Claiming
and teaming is not currently possible. So I have to stay on the older
versions for now until it gets fixed.

**Comment by sarcastic6** [comment]
Just wanted to +1 this, as the newest version of FTBU very broken so I'm running an older one as well.  This worked fine until the newest version of CarryOn.

Between https://github.com/LatvianModder/FTBUtilities/issues/666 and https://github.com/LatvianModder/FTBUtilities/issues/668, the required version FTBU is essentially useless.

**Comment by Tschipp** [comment]
@kreezxil Unfortunately, FTBU for some reason restructures their code quite frequently, which ruins backwards compatibility. The last version of carry on (1.7) still supports older FTBU sub 5.0, but if it were to be used with latest FTBU, it would crash. So I made the descision on enforcing a certain version of FTBU so that these crashes wouldn't happen.
I'm not quite sure what to do about this. If I don't update the version, that's gonna cause issues further down the line. I didn't know that latest FTBU still was so buggy, since they changed the state from alpha to release.
If you want to have almost the same experience as Carry On 1.8 with 1.7, you can download the "Container Fix" mod and add the mods that I listed on the changelog to the blacklist.

**Comment by kreezxil** [comment]
Can't you duplicate the part of the ftbu library code you need internally
into your mod. That's really a lot of code to require. Plus FTBU forces
teams and claiming, and quite a few other tools on a pack that a modpack
developer might not desire. For instance I started with mycommands mod, but
because some mod other than yours required FTBU I now have duplicate
commands in my system. All because that other mod wanted FTBU as a
dependency.

**Comment by Tschipp** [comment]
If you don't want to use FTBU, don't use it. It's not a hard dependecy (or at least it shouldn't be). If FTBU has  Issues or you have other feature requests, I suggest you take it to them.
