### ISSUE TITLE
Error when you try to pick up a crushing basin from the rustic mod which has liquid in it. Liquid empties and block remains with error.

### ISSUE THREAD

**Issue by WheresMyMtnDew** [Tschipp/CarryOn#95]

**Comment by Saberawr** [comment]
Expected Behaviour: Crushing Tub gets picked up with liquid & items in it to be re-placed again.
Actual Behaviour: Liquid & items in tub voided & tub remains in place
Steps to reproduce: empty hand carry-on key on tub with items & liquid inside
Versions: Minecraft 1.12.2, Carry On 1.8, Forge 14.23.2.2651

**Comment by Tatsu-Kishi** [comment]
The same happens with the Apiary from Rustic: Block stays where it is but it's contents are voided.
Versions: MC 1.12.2, Forge 14.23.2.2651, CarryOn 1.8, Rustic 1.0.3
