### ISSUE TITLE
Animania piglet taking up entire screen

### ISSUE THREAD

**Issue by polartwins** [Tschipp/CarryOn#98]
### Expected Behavior
Piglet being visible when held but still allowing me to see where I am going

### Actual Behavior
Entire screen is covered with the piglet's texture; I'm unable to see anything but that.

### Steps to Reproduce
1. Pick up piglet

### Version of Minecraft, Carry On, Forge
Minecraft: 1.12.2
Carry On: 1.8
Forge: 14.23.3.2655
Animania: 1.4.8

### Screenshots encouraged
![2018-04-29_18 37 40](https://user-images.githubusercontent.com/27713689/39413355-c1565da4-4bdd-11e8-9a67-fd3c0793d1e2.png)
![2018-04-29_18 37 38](https://user-images.githubusercontent.com/27713689/39413356-c418dc6a-4bdd-11e8-9efb-210e3e976d97.png)

**Comment by Tschipp** [comment]
Yeah that's because Animania does funky stuff when rendering the aging of animals, the animals become larger but the hitbox doesn't (which is also not possible to my knowledge). Since the positioning of the animal depends on the hitbox, there isn't really much that I can do without having to make special exceptions for Animania. So this will be a wontfix on here, but I'll try to resolve this by finding a way to do the hitbox stuff in animania.
